#!/usr/bin/env bash
# tests_stress.sh — Section L: Large response stress tests.
#
# Exercises zoqa's HTTP client with large API responses generated by
# the stress.pm test module.  The module uses record_info() in a loop
# to inflate the jobs/ID/details endpoint response to configurable sizes.
#
# DEFAULT SIZE:  800 steps * 50 KB = ~38 MB  (adjustable via env vars
# E2E_STRESS_STEPS and E2E_STRESS_TEXT_SIZE on the host side).
#
# TESTS:
#   1. Response size sanity check — FAIL if details response < 30 MB.
#   2. Output parity — HARD FAIL if Perl and Zig outputs differ on
#      jobs/$STRESS_JOB_ID/details (large response).
#   3. Gzip negotiation — FAIL if zoqa does NOT send Accept-Encoding
#      containing "gzip" in --verbose output.  Expected to FAIL before
#      the Accept-Encoding fix and PASS after.
#
# INFORMATIONAL (no PASS/FAIL):
#   4. Wall-clock timing for both implementations.
#   5. Peak RSS via /usr/bin/time -v for both implementations.
#   6. Gzip server response — INFO line noting whether the server
#      actually responded with Content-Encoding: gzip.
#
# PREREQUISITES inside the container:
#   - /usr/bin/time  (installed by setup.sh)
#   - bash, grep, cut, tr, awk/gawk
#
# Sourced by tests.sh after helper functions are defined.
# Do NOT execute this file directly.
#
# Assumes from the calling scope:
#   ZIG_EXE, PERL_EXE, LOG_DIR,
#   GROUP_ID, OPENQA_API_KEY, OPENQA_API_SECRET
#   run_test(), run_diff_test(), container_exec()
#   failed_tests, warned_tests

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

echo "==> [stress] Running large response stress tests..."

# Schedule and wait for the stress job (lazy-init, reuses if already done).
ensure_stress_job "${E2E_STRESS_STEPS:-800}" "${E2E_STRESS_TEXT_SIZE:-50000}"

# -------------------------------------------------------------------------
# Test: Response size sanity check
# -------------------------------------------------------------------------
echo "--- Test: Stress job details response size ---"
_stress_resp_size=$(container_exec bash -c \
	"$PERL_EXE api --host http://localhost jobs/$STRESS_JOB_ID/details 2>/dev/null | wc -c")
# Strip whitespace (wc -c may pad with spaces)
_stress_resp_size=$(echo "$_stress_resp_size" | tr -d ' \t')
echo "Details response size: $_stress_resp_size bytes"

_stress_min_size=$((30 * 1024 * 1024))
if [[ "$_stress_resp_size" -ge "$_stress_min_size" ]]; then
	echo "PASS (response >= 30 MB)"
else
	echo "FAIL: Response too small ($_stress_resp_size < $_stress_min_size bytes)"
	failed_tests=$((failed_tests + 1))
fi

# -------------------------------------------------------------------------
# Test: Output parity (Perl vs Zig) on large response
# -------------------------------------------------------------------------
run_diff_test "GET jobs/$STRESS_JOB_ID/details output parity (large)" \
	"jobs/$STRESS_JOB_ID/details"

# -------------------------------------------------------------------------
# Test: Gzip negotiation — zoqa must send Accept-Encoding containing "gzip"
#
# This test is expected to FAIL with the current code (which sends
# "Accept-Encoding: identity") and PASS after Fix 1 is applied.
# -------------------------------------------------------------------------
echo "--- Test: ZIG : gzip negotiation (Accept-Encoding header) ---"
container_exec bash -c \
	"$ZIG_EXE api --host http://localhost --verbose jobs/$STRESS_JOB_ID/details" \
	>/dev/null 2>"$LOG_DIR/stress_gzip_verbose.log"

# --verbose prints request headers to stderr.  Look for the Accept-Encoding
# header line containing "gzip".
if grep -qi 'accept-encoding.*gzip' "$LOG_DIR/stress_gzip_verbose.log"; then
	echo "PASS (zoqa sends Accept-Encoding containing gzip)"
else
	echo "FAIL: zoqa does not send Accept-Encoding containing gzip"
	echo "  (expected to fail before Accept-Encoding fix is applied)"
	# Show what was actually sent for diagnostic purposes
	grep -i 'accept-encoding' "$LOG_DIR/stress_gzip_verbose.log" 2>/dev/null ||
		echo "  (no Accept-Encoding header found in verbose output)"
	failed_tests=$((failed_tests + 1))
fi

# -------------------------------------------------------------------------
# Informational: Did the server respond with gzip compression?
# -------------------------------------------------------------------------
if grep -qi 'content-encoding.*gzip' "$LOG_DIR/stress_gzip_verbose.log"; then
	echo "INFO: Server responded with Content-Encoding: gzip"
else
	echo "INFO: Server did NOT respond with Content-Encoding: gzip"
	echo "  (Apache mod_deflate may not be enabled for application/json)"
fi

# =========================================================================
# Informational: Performance comparison (wall-clock + peak RSS)
#
# No PASS/FAIL — results are printed in a summary block at the end.
# These numbers provide "before" baselines for the HTTP client fixes.
# =========================================================================
echo ""
echo "--- Info: Stress response performance comparison ---"

# --- helpers (scoped to this file) ---
_stress_wall_time_s() {
	local cmd=$1
	container_exec bash -c "
TIMEFORMAT='%R'
{ time $cmd >/dev/null 2>&1; } 2>/tmp/_stress_wall.out
cat /tmp/_stress_wall.out
" 2>/dev/null
}

_stress_peak_rss_kb() {
	local cmd=$1
	local tag=$2

	container_exec bash -c \
		"/usr/bin/time -v $cmd >/dev/null 2>/tmp/_stress_timev_${tag}.txt" \
		</dev/null 2>/dev/null || true

	container_exec bash -c \
		"grep 'Maximum resident set size' /tmp/_stress_timev_${tag}.txt | cut -d: -f2 | tr -d ' \t'" \
		</dev/null 2>/dev/null
}

_stress_timev_field() {
	local tag=$1
	local field=$2
	container_exec bash -c \
		"grep '$field' /tmp/_stress_timev_${tag}.txt 2>/dev/null | cut -d: -f2 | tr -d ' \t'" \
		</dev/null 2>/dev/null
}

# --- Wall-clock timing (single run each — large responses are slow) ---
_stress_api_args="jobs/$STRESS_JOB_ID/details"

_stress_perl_time=$(_stress_wall_time_s \
	"$PERL_EXE api --host http://localhost $_stress_api_args")
_stress_zig_time=$(_stress_wall_time_s \
	"$ZIG_EXE api --host http://localhost $_stress_api_args")

echo "  Wall-clock:  PERL ${_stress_perl_time}s   ZIG ${_stress_zig_time}s"

if [[ -n "$_stress_perl_time" && -n "$_stress_zig_time" &&
	"$_stress_perl_time" != "0.000" && "$_stress_zig_time" != "0.000" ]]; then
	_stress_cmp=$(container_exec bash -c "awk 'BEGIN {
		p=$_stress_perl_time; z=$_stress_zig_time;
		if (z < p) {
			printf \"INFO: Zig is %.1f%% faster (%.1fx speedup)\", (p-z)/p*100, p/z;
		} else {
			printf \"INFO: Zig is %.1f%% slower (%.1fx slowdown)\", (z-p)/p*100, z/p;
		}
	}'")
	echo "  $_stress_cmp"
fi

# --- Peak RSS ---
_stress_perl_rss=$(_stress_peak_rss_kb \
	"$PERL_EXE api --host http://localhost $_stress_api_args" "stress_perl")
_stress_zig_rss=$(_stress_peak_rss_kb \
	"$ZIG_EXE api --host http://localhost $_stress_api_args" "stress_zig")

echo "  Peak RSS:    PERL ${_stress_perl_rss:-?} kB   ZIG ${_stress_zig_rss:-?} kB"

# Additional metrics from /usr/bin/time -v
_stress_perl_user=$(_stress_timev_field "stress_perl" "User time")
_stress_zig_user=$(_stress_timev_field "stress_zig" "User time")
_stress_perl_sys=$(_stress_timev_field "stress_perl" "System time")
_stress_zig_sys=$(_stress_timev_field "stress_zig" "System time")
_stress_perl_minor=$(_stress_timev_field "stress_perl" "Minor .reclaiming a frame. page faults")
_stress_zig_minor=$(_stress_timev_field "stress_zig" "Minor .reclaiming a frame. page faults")

echo "  User time:   PERL ${_stress_perl_user:-?}s   ZIG ${_stress_zig_user:-?}s"
echo "  System time: PERL ${_stress_perl_sys:-?}s   ZIG ${_stress_zig_sys:-?}s"
echo "  Minor faults: PERL ${_stress_perl_minor:-?}   ZIG ${_stress_zig_minor:-?}"

echo ""
echo "  Response size: $_stress_resp_size bytes"
echo "  Stress config: STEPS=${E2E_STRESS_STEPS:-800} TEXT_SIZE=${E2E_STRESS_TEXT_SIZE:-50000}"
